language: ruby
bundler_args: --without development production
rvm:
- 2.1.2
script:
- RAILS_ENV=test COVERAGE=true bundle exec rake db:setup spec
services: postgresql
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 7dc15a9256eba01ea8fe748827ce385fae50672d8a500d7159e8a065c0bbe879
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - taylormartin.uga@gmail.com
    on_success: change
    on_failure: always