
development:
  adapter: postgresql
  encoding: utf8
  database: lunchbot_dev
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: lunchbot_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: lunchbot_app
  pool: 5